DROP VIEW IF EXISTS jos_view_export;
CREATE VIEW `jos_view_export` AS
SELECT 
EmployeeFirstName as  EmployeeFirstName,
EmployeeLastName as  EmployeeLastName,
EmployeeID_SSN as EmployeeID_SSN,
Address1 as StreetAddress1,
City as City,
State as State,
Zip as Zip,
'' as EEOfferCoverageCode_All,
MAX(CASE WHEN Month = 1 AND CoveredIndividualID_SSN = EmployeeID_SSN  THEN OfferofCoverageCode END) as EEOfferCoverageCode_Jan,
MAX(CASE WHEN Month = 2 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Feb,
MAX(CASE WHEN Month = 3 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Mar,
MAX(CASE WHEN Month = 4 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Apr,
MAX(CASE WHEN Month = 5 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END)  as EEOfferCoverageCode_May,
MAX(CASE WHEN Month = 6 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Jun,
MAX(CASE WHEN Month = 7 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Jul,
MAX(CASE WHEN Month = 8 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Aug,
MAX(CASE WHEN Month = 9 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Sep,
MAX(CASE WHEN Month = 10 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Oct,
MAX(CASE WHEN Month = 11 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_Nov,
MAX(CASE WHEN Month = 12 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN OfferofCoverageCode END) as EEOfferCoverageCode_dec,
'' as MinPremAmtOfferedtoEEatEmployerRate_All,
MAX(CASE WHEN Month = 1 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Jan,
MAX(CASE WHEN Month = 2 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Feb,
MAX(CASE WHEN Month = 3 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Mar,
MAX(CASE WHEN Month = 4 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Apr,
MAX(CASE WHEN Month = 5 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END)  as MinPremAmtOfferedtoEEatEmployerRate_May,
MAX(CASE WHEN Month = 6 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Jun,
MAX(CASE WHEN Month = 7 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Jul,
MAX(CASE WHEN Month = 8 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Aug,
MAX(CASE WHEN Month = 9 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Sep,
MAX(CASE WHEN Month = 10 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Oct,
MAX(CASE WHEN Month = 11 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_Nov,
MAX(CASE WHEN Month = 12 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN MinPremAmtOfferedtoEEatEmployerRate END) as MinPremAmtOfferedtoEEatEmployerRate_dec,
'' as SafeHarborCodeA_ll,
MAX(CASE WHEN Month = 1 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Jan,
MAX(CASE WHEN Month = 2 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Feb,
MAX(CASE WHEN Month = 3 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Mar,
MAX(CASE WHEN Month = 4 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Apr,
MAX(CASE WHEN Month = 5 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END)  as SafeHarborCode_May,
MAX(CASE WHEN Month = 6 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Jun,
MAX(CASE WHEN Month = 7 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Jul,
MAX(CASE WHEN Month = 8 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Aug,
MAX(CASE WHEN Month = 9 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Sep,
MAX(CASE WHEN Month = 10 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Oct,
MAX(CASE WHEN Month = 11 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_Nov,
MAX(CASE WHEN Month = 12 AND CoveredIndividualID_SSN = EmployeeID_SSN THEN SafeHarborCode END) as SafeHarborCode_dec,

-- Part3 Covered Ind. 1  Typically is the Employee
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN CONCAT(CoveredFirstName, ' ', CoveredLastName) END  as  NameCovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN CoveredIndividualID_SSN END  as  SSNCovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN DateofBirth END  as  DOBCovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovAllMonthsCovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovJan_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovFeb_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovMar_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovApr_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovJun_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovJul_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovAug_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovSep_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovOct_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovNov_CovInd_1,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovDec_CovInd_1,


-- Part3 Covered Ind. 2  
MAX(CASE WHEN Relationship_Others = 1 AND EmployeeID_SSN_Others = EmployeeID_SSN THEN NameCovInd_Others  END)  as  NameCovInd_2,
MAX(CASE WHEN Relationship_Others = 1 AND EmployeeID_SSN_Others = EmployeeID_SSN THEN CoveredIndividualID_SSN_Others  END)   as  SSNCovInd_2,
MAX(CASE WHEN Relationship_Others = 1 AND EmployeeID_SSN_Others = EmployeeID_SSN THEN DateofBirth_Others  END)  as  DOBCovInd_2,
CASE WHEN CoveredIndividualID_SSN = EmployeeID_SSN THEN '' END  as  CovAllMonthsCovInd_2,
MAX(CASE WHEN MonthOthers = 1 AND Relationship_Others = 1 AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovJan_CovInd_2,
MAX(CASE WHEN MonthOthers = 2 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovFeb_CovInd_2,
MAX(CASE WHEN MonthOthers = 3 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovMar_CovInd_2,
MAX(CASE WHEN MonthOthers = 4 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovApr_CovInd_2,
MAX(CASE WHEN MonthOthers = 5 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovMay_CovInd_2,
MAX(CASE WHEN MonthOthers = 6 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovJun_CovInd_2,
MAX(CASE WHEN MonthOthers = 7 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)   as  CovJul_CovInd_2,
MAX(CASE WHEN MonthOthers = 8 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovAug_CovInd_2,
MAX(CASE WHEN MonthOthers = 9 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovSep_CovInd_2,
MAX(CASE WHEN MonthOthers = 10 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovOct_CovInd_2,
MAX(CASE WHEN MonthOthers = 11 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovNov_CovInd_2,
MAX(CASE WHEN MonthOthers = 12 AND Relationship_Others = 1  AND EmployeeID_SSN_Others = EmployeeID_SSN THEN EEOfferCoverageCode_Others  END)  as  CovDec_CovInd_2



FROM dyi.jos_importdata
inner join jos_view_cov_ind on jos_view_cov_ind.EmployeeID_SSN_Others = jos_importdata.EmployeeID_SSN
group by EmployeeID_SSN
